### ISSUE TITLE
it is black screen even in iframe

### ISSUE THREAD

**Issue by sarvarkhuja** [HumeAI/empathic-voice-embed-renderer#23]
Hello

Even it is in iframe, it is in black screen
https://iframetester.com/?url=https://voice-widget.hume.ai/

**Comment by yinishi** [comment]
Hi @sarvarkhuja, the voie widget renders in a 50x50 iframe in the bottom right of the parent web application, and needs to be used in conjunction with the `@humeai/voice-embed-react` npm package. Please see the [Embedding the widget in your own tool
](https://github.com/HumeAI/empathic-voice-embed-renderer?tab=readme-ov-file#embedding-the-widget-in-your-own-tool) for more information.
